Repository fhac-ewi/grid-optimizer, pull requests merged in 2021-04, with the labels that each got.

#3 CI/CD Workflows for test, release and deploy
  .github/release-changelog-configuration.json
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: enhancement

#8 Changed backend to match developer frontend server port (3000)
  .github/workflows/pr-delete-deploy.yml
  README.md
  src/Application.kt
Labels: fix

#16 CI build improvements
  .github/workflows/deploy.yml
  .github/workflows/pr-deploy.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: fix

#13 Added Grid Data Model
  src-frontend/package.json
  src-frontend/src/App.css
  src-frontend/src/App.tsx
  src-frontend/src/CustomNodes/InputNode.tsx
  src-frontend/src/CustomNodes/IntermediateNode.tsx
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/Filemanagement/FileDownload.tsx
  src-frontend/src/Filemanagement/FileUpload.tsx
  src-frontend/src/Filemanagement/file-download.css
  src-frontend/src/Filemanagement/file-upload.css
  src-frontend/src/FlowContainer.tsx
  src-frontend/src/Overlays/EdgeContextOverlay.tsx
  src-frontend/src/Overlays/EdgePopover.tsx
  src-frontend/src/Overlays/NodeContextOverlay.tsx
  src-frontend/src/Overlays/Notifications.tsx
  src-frontend/src/UserTour/UserTour.tsx
  src-frontend/src/mock/GridMock.json
  src-frontend/src/models.ts
  src-frontend/src/utils/BrowserChecker.ts
  src-frontend/src/utils/utility.tsx
  src-frontend/yarn.lock
  src/Application.kt
  src/dto/GridRequest.kt
  src/dto/InputNodeRequest.kt
  src/dto/IntermediateNodeRequest.kt
  src/dto/OptimizationRequest.kt
  src/dto/OutputNodeRequest.kt
  src/dto/PipeRequest.kt
  src/exceptions/IllegalGridException.kt
  src/model/Grid.kt
  src/model/InputNode.kt
  src/model/IntermediateNode.kt
  src/model/LoadProfile.kt
  src/model/Node.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/routes/GridRoute.kt
  src/services/GridService.kt
  src/util/GridUtil.kt
  src/util/RuntimeTypeAdapterFactory.kt
  test/model/GridTest.kt
  test/model/InputNodeTest.kt
  test/model/IntermediateNodeTest.kt
  test/model/OutputNodeTest.kt
  test/model/PipeTest.kt
  test/routes/GridRoute.kt
  test/services/GridServiceTest.kt
Labels: enhancement

#21 Allow cors in development mode
  src/Application.kt
Labels: enhancement

#29 Return 400 BadRequest on illegal input parameters
  src/Application.kt
Labels: backend, enhancement

#27 Added utils to execute mathematical functions
  src/util/EngineUtil.kt
  test/util/EngineUtilTest.kt
Labels: backend, enhancement

#31 Added more input parameters to grid model
  src/Application.kt
  src/dto/InputNodeRequest.kt
  src/dto/OptimizationRequest.kt
  src/dto/OutputNodeRequest.kt
  src/model/Grid.kt
  src/model/InputNode.kt
  src/model/LoadProfile.kt
  src/model/OutputNode.kt
  src/services/GridService.kt
  src/util/RuntimeTypeAdapterFactory.kt
  test/model/GridTest.kt
  test/model/InputNodeTest.kt
Labels: backend, enhancement

#35 Feature/upload csv
  src-frontend/package.json
  src-frontend/src/App.css
  src-frontend/src/App.tsx
  src-frontend/src/Filemanagement/FileUpload.tsx
  src-frontend/src/MetaData/MetaDataContainer.tsx
  src-frontend/src/UserTour/UserTour.tsx
  src-frontend/src/pipe.tsx
  src-frontend/yarn.lock
Labels: enhancement, frontend

#32 Added standard load profiles to distribute thermal energy demand
  resources/standard-load-profiles.csv
  src/Application.kt
  src/dto/OutputNodeRequest.kt
  src/model/Grid.kt
  src/model/HeatDemandCurve.kt
  src/model/IntermediateNode.kt
  src/model/LoadProfile.kt
  src/model/Node.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/routes/StandardLoadProfileRoute.kt
  src/routes/TemperatureRoute.kt
  src/services/GridService.kt
  src/services/LoadProfileService.kt
  src/util/RessourceUtil.kt
  test/model/GridTest.kt
  test/model/InputNodeTest.kt
  test/model/OutputNodeTest.kt
  test/routes/GridRoute.kt
  test/services/GridServiceTest.kt
  test/services/TemperatureTimeSeriesServiceTest.kt
  test/util/RessourceUtilTest.kt
Labels: backend, enhancement

#36 Improved error handling in backend
  src/Application.kt
  src/routes/GridRoute.kt
  src/util/ExceptionUtil.kt
Labels: backend, enhancement

#37 Added maximum Massenstrom calculation for grid
  src/Application.kt
  src/dto/MassenstromResponse.kt
  src/model/Grid.kt
  src/model/HeatDemandCurve.kt
  src/routes/GridRoute.kt
  src/services/GridService.kt
  src/util/GridUtil.kt
  src/util/MathUtil.kt
  test/services/GridServiceTest.kt
Labels: backend, enhancement
