Repository fhac-ewi/grid-optimizer, pull requests merged in 2021-06, with the labels that each got.

#107 Added more grid tests
  test/routes/GridRoute.kt
  test/routes/GridRouteTest.kt
Labels: backend

#111 Improved frontend handling
  src-frontend/src/App.tsx
  src-frontend/src/Components/AbortButton.tsx
  src-frontend/src/Components/ConfirmationButton.tsx
  src-frontend/src/Components/CustomSelect.tsx
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/FlowContainer.tsx
  src-frontend/src/OptimizationResults.tsx
  src-frontend/src/Overlays/FormSkeleton.tsx
  src-frontend/src/Overlays/NodeContextOverlay.tsx
Labels: enhancement, frontend

#112 Improved view Meta for grid optimization
  src-frontend/src/App.tsx
  src-frontend/src/MetaData/MetaDataContainer.tsx
  src-frontend/src/defaultConfig.ts
  src-frontend/src/models.ts
  src-frontend/src/utils/defaults.ts
Labels: enhancement, frontend

#123 Fixed units in formula massenstrom
  src/util/MathUtil.kt
Labels: backend, fix

#121 Fixed heat profile distribution
  src-frontend/src/App.tsx
  src-frontend/src/Components/LoadProfileSelect.tsx
  src-frontend/src/FormulaCheck.tsx
  src-frontend/src/MetaData/MetaDataContainer.tsx
  src-frontend/src/Overlays/NodeContextOverlay.tsx
  src-frontend/src/index.css
  src-frontend/src/models.ts
  src-frontend/src/utils/defaults.ts
  src-frontend/yarn.lock
  src/Application.kt
  src/dto/HeatDemandRequest.kt
  src/model/heatprofile/LoadProfile.kt
  src/routes/HeatDemandRoute.kt
  src/routes/StandardLoadProfileRoute.kt
  src/services/HeatDemandService.kt
  src/util/MathUtil.kt
Labels: backend, fix, frontend

#133 Provide better error messages
  src/exceptions/IllegalRequestException.kt
  src/model/Grid.kt
  src/routes/GridRoute.kt
  src/routes/OptimizeRoute.kt
  src/services/GridService.kt
  src/services/OptimizerService.kt
  src/util/EngineUtil.kt
  src/util/ExceptionUtil.kt
Labels: backend, enhancement

#134 Renamed some labels in frontend
  src-frontend/src/App.tsx
  src-frontend/src/MetaData/MetaDataContainer.tsx
  src-frontend/src/VersionNumber.tsx
Labels: enhancement, frontend

#135 Changed order of menu icons
  src-frontend/src/App.tsx
Labels: fix, frontend

#142 Include heat loss in optimization
  src-frontend/src/Components/DefaultEdge.tsx
  src-frontend/src/MetaData/PipeTypeForm.tsx
  src-frontend/src/ReactFlow/FlowContainer.tsx
  src-frontend/src/ReactFlow/Overlays/EdgeContextOverlay.tsx
  src-frontend/src/ReactFlow/Overlays/EdgePopover.tsx
  src-frontend/src/models.ts
  src-frontend/src/utils/defaults.ts
  src/dto/PipeRequest.kt
  src/dto/PipeTypeRequest.kt
  src/model/Costs.kt
  src/model/Grid.kt
  src/model/InputNode.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/Pipe.kt
  src/model/PipeType.kt
  src/services/GridService.kt
  src/services/OptimizerService.kt
  src/util/EngineUtil.kt
  src/util/MathUtil.kt
  test/model/GridOptimizerTest.kt
  test/model/GridTest.kt
  test/model/InputNodeTest.kt
  test/model/IntermediateNodeTest.kt
  test/model/OutputNodeTest.kt
  test/model/PipeTest.kt
  test/services/GridServiceTest.kt
Labels: backend, enhancement, frontend

#147 Added output node replicas
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/ReactFlow/Overlays/NodeContextOverlay.tsx
  src-frontend/src/models.ts
  src/dto/OutputNodeRequest.kt
  src/services/GridService.kt
Labels: enhancement

#148 Forced parsing engine result to double
  src/util/EngineUtil.kt
Labels: backend, bug, fix

#157 Improved performance in backend
  src/model/HeatDemandCurve.kt
  src/model/InputNode.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/model/PipeOptimizer.kt
  src/util/ListUtil.kt
  test/util/PerformanceTest.kt
Labels: enhancement

#160 Changed default for pump invest cost formula close #153
  src-frontend/src/utils/defaults.ts
  test/model/GridOptimizerTest.kt
Labels: fix

#163 Fixed heat demand unit
  src/dto/OutputNodeRequest.kt
  src/model/HeatDemandCurve.kt
  src/model/OutputNode.kt
  src/services/GridService.kt
  src/util/MathUtil.kt
Labels: backend, fix

#167 Added IDs in error messages
  src/model/InputNode.kt
  src/model/Node.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
Labels: enhancement

#169 Improve UI design
  src-frontend/src/App.tsx
  src-frontend/src/Components/AbortButton.tsx
  src-frontend/src/Components/ConfirmationButton.tsx
  src-frontend/src/Components/DeleteButton.tsx
  src-frontend/src/CustomNodes/InputNode.tsx
  src-frontend/src/CustomNodes/IntermediateNode.tsx
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/Filemanagement/FileDownload.tsx
  src-frontend/src/Filemanagement/FileUpload.tsx
  src-frontend/src/Filemanagement/file-upload.css
  src-frontend/src/ReactFlow/FlowContainer.tsx
  src-frontend/src/ReactFlow/OverlayButtons/CostView.tsx
  src-frontend/src/ReactFlow/OverlayButtons/NodeMenu/NodeMenuSpawnerContainer.tsx
  src-frontend/src/ReactFlow/Overlays/FormSkeleton.tsx
  src-frontend/src/ReactFlow/Overlays/NodeContextOverlay.tsx
Labels: enhancement

#141 Visualize detailed node optimization
  src-frontend/package-lock.json
  src-frontend/package.json
  src-frontend/src/App.tsx
  src-frontend/src/Components/ConfirmationButton.tsx
  src-frontend/src/Components/DefaultEdge.tsx
  src-frontend/src/Components/DeleteButton.tsx
  src-frontend/src/CustomNodes/InputNode.tsx
  src-frontend/src/CustomNodes/IntermediateNode.tsx
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/Filemanagement/FileDownload.tsx
  src-frontend/src/Filemanagement/FileUpload.tsx
  src-frontend/src/Filemanagement/file-upload.css
  src-frontend/src/OptimizationNode/OptimizationNodeDetails.tsx
  src-frontend/src/ReactFlow/FlowContainer.tsx
  src-frontend/src/ReactFlow/OverlayButtons/CostView.tsx
  src-frontend/src/ReactFlow/OverlayButtons/OptimizeButton.tsx
  src-frontend/src/ReactFlow/Overlays/EdgeContextOverlay.tsx
  src-frontend/src/ReactFlow/Overlays/EdgePopover.tsx
  src-frontend/src/ReactFlow/Overlays/FormSkeleton.tsx
  src-frontend/src/ReactFlow/Overlays/NodeContextOverlay.tsx
  src-frontend/src/models.ts
  src-frontend/src/utils/defaults.ts
  src-frontend/yarn.lock
  src/dto/OutputNodeRequest.kt
  src/model/HeatDemandCurve.kt
  src/model/InputNode.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/model/PipeOptimizer.kt
  src/services/GridService.kt
  src/util/EngineUtil.kt
  src/util/ListUtil.kt
  src/util/MathUtil.kt
  test/model/GridOptimizerTest.kt
  test/routes/GridRouteTest.kt
  test/util/PerformanceTest.kt
Labels: enhancement, frontend

#170 Added pipe heat loss to thermal energy demand
  src/model/HeatDemandCurve.kt
  src/model/Node.kt
Labels: backend, enhancement

#171 Added pressure loss for return flow
  src/model/Pipe.kt
Labels: enhancement

#173 Added delegates to increase optimization performance
  src/Application.kt
  src/dto/MassenstromResponse.kt
  src/dto/OptimizedNodeResponse.kt
  src/dto/OptimizedPipeResponse.kt
  src/model/Grid.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/model/PipeType.kt
  src/model/delegate/CalculableDelegate.kt
  src/model/delegate/PipeBasedCalculableDelegate.kt
  src/model/delegate/SubscribableDelegate.kt
  src/model/math/NodeEnergyDemandDelegate.kt
  src/model/math/NodePressureLossDelegate.kt
  src/model/math/NodePumpPowerDelegate.kt
  src/model/math/PipeEnergyDemandDelegate.kt
  src/model/math/PipeFlowRateDelegate.kt
  src/model/math/PipeHeatLossDelegate.kt
  src/model/math/PipePressureLossDelegate.kt
  src/model/math/PipePumpPowerDelegate.kt
  src/model/math/PipeTotalPressureLossDelegate.kt
  src/model/math/PipeVolumeFlowDelegate.kt
  src/services/GridService.kt
  src/services/OptimizerService.kt
  src/util/DelegateUtil.kt
  src/util/MathUtil.kt
  test/model/GridOptimizerTest.kt
  test/routes/OptimizationRouteTest.kt
Labels: backend, enhancement

#176 Changed order of executed pipe type checks in optimization
  src/model/InputNode.kt
  src/model/InvestmentParameter.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/services/OptimizerService.kt
  test/model/GridOptimizerTest.kt
Labels: enhancement

#186 Reorganized some code
  src/exceptions/IllegalRequestException.kt
  src/model/Grid.kt
  src/model/HeatDemandCurve.kt
  src/model/InputNode.kt
  src/model/InvestmentParameter.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/PipeType.kt
  src/model/delegate/PipeBasedCalculableDelegate.kt
  src/model/heatprofile/LoadProfile.kt
  src/model/math/NodeEnergyDemandDelegate.kt
  src/model/math/NodePressureLossDelegate.kt
  src/model/math/NodePumpPowerDelegate.kt
  src/model/math/PipeFlowRateDelegate.kt
  src/model/math/PipeHeatLossDelegate.kt
  src/model/math/PipePressureLossDelegate.kt
  src/model/math/PipePumpPowerDelegate.kt
  src/model/math/PipeVolumeFlowDelegate.kt
  src/services/GridService.kt
  src/util/DelegateUtil.kt
  src/util/MathUtil.kt
  test/model/GridOptimizerTest.kt
  test/model/GridTest.kt
  test/model/InputNodeTest.kt
  test/routes/GridRouteTest.kt
  test/routes/OptimizationRouteTest.kt
  test/util/PerformanceTest.kt
Labels: backend, enhancement

#187 Improved output of optimization
  src-frontend/src/App.tsx
  src-frontend/src/Components/DefaultEdge.tsx
  src-frontend/src/CustomNodes/InputNode.tsx
  src-frontend/src/CustomNodes/IntermediateNode.tsx
  src-frontend/src/CustomNodes/OutputNode.tsx
  src-frontend/src/OptimizationNode/OptimizationNodeDetails.tsx
  src-frontend/src/OptimizationResults.tsx
  src-frontend/src/ReactFlow/FlowContainer.tsx
  src-frontend/src/ReactFlow/OverlayButtons/OptimizeButton.tsx
  src-frontend/src/models.ts
  src/dto/OptimizationResponse.kt
  src/dto/OptimizedNodeResponse.kt
  src/dto/OptimizedPipeResponse.kt
  src/services/OptimizerService.kt
Labels: backend, enhancement, frontend

#192 Added calculation of reynolds number
  src/util/MathUtil.kt
Labels: enhancement

#191 Changed critical path to longest path
  src/model/Grid.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/services/OptimizerService.kt
Labels: backend, fix

#194 Changed initial value on PipeBasedCalculableDelegate
  src/model/delegate/PipeBasedCalculableDelegate.kt
Labels: backend, fix

#196 Fixed calculation of pump power in node
  src/model/Node.kt
  src/model/math/NodePumpPowerDelegate.kt
  src/model/math/NodeVolumeFlowDelegate.kt
Labels: backend, fix

#195 Updated simple grid test with realistic values
  test/model/GridOptimizerTest.kt
Labels: backend

#197 Fixed wrong unit of heat demand in Massenstrom
  src/util/MathUtil.kt
Labels: backend, fix

#202 Changed calculation of volume flow
  src/model/math/PipeVolumeFlowDelegate.kt
Labels: backend, fix

#208 Fixed unit in pump invest cost
  src/model/InvestmentParameter.kt
  test/model/GridOptimizerTest.kt
Labels: fix

#216 Fixed reynolds number in Übergangsbereich
  src/util/MathUtil.kt
Labels: backend, bug, fix

#223 Added replica nodes to decrease number of pipes
  src/model/Grid.kt
  src/model/InvestmentParameter.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/OutputNode.kt
  src/model/Pipe.kt
  src/model/ReplicaOutputNode.kt
  src/model/ReplicaPipe.kt
  src/model/math/PipeVolumeFlowDelegate.kt
  src/model/math/ReplicaPipeEnergyDemandDelegate.kt
  src/model/strategies/AllCombinations.kt
  src/model/strategies/ChildNodesOfPipe.kt
  src/model/strategies/CriticalPathAsOne.kt
  src/model/strategies/CriticalPathOneByOne.kt
  src/model/strategies/CriticalPathToMaxPascal.kt
  src/model/strategies/IslandStrategy.kt
  src/model/strategies/PathToSourceAsOne.kt
  src/model/strategies/PathToSourceOneByOne.kt
  src/model/strategies/RepeatAllOneByOne.kt
  src/model/strategies/V3Strategy.kt
  src/services/GridService.kt
  test/model/ReplicaTest.kt
Labels: backend, enhancement

#226 Rework optimizer
  resources/temperature-time-series.csv
  src/model/Optimizer.kt
  src/model/OptimizerParameter.kt
  src/model/strategies/AllCombinations.kt
  src/model/strategies/CrazyStrategy.kt
  src/model/strategies/CriticalPathOneByOneReversed.kt
  src/model/strategies/DoNothing.kt
  src/model/strategies/IncreaseAllPipesByOne.kt
  src/model/strategies/LayerDownToOneByOne.kt
  src/model/strategies/LowerHeatLoss.kt
  src/model/strategies/LowerHeatLoss2.kt
  src/model/strategies/LowerPressureLoss.kt
  src/model/strategies/LowerPressureLoss10.kt
  src/model/strategies/LowerPressureLoss2.kt
  src/model/strategies/LowerPressureLoss3.kt
  src/model/strategies/LowerPressureLoss4.kt
  src/model/strategies/LowerPressureLoss5.kt
  src/model/strategies/LowerPressureLoss6.kt
  src/model/strategies/LowerPressureLoss7.kt
  src/model/strategies/LowerPressureLoss8.kt
  src/model/strategies/LowerPressureLoss9.kt
  src/model/strategies/PathToSourceOneByOne.kt
  src/model/strategies/PathToSourceOneByOneFast.kt
  src/util/DoubleArrayUtil.kt
  test/model/GridOptimizerTest.kt
  test/util/RessourceUtilTest.kt
Labels: backend, enhancement

#233 Improved visual experience
  src-frontend/src/App.css
  src-frontend/src/App.tsx
  src-frontend/src/CustomNodes/InputNode.tsx
  src-frontend/src/FormulaCheck.tsx
  src-frontend/src/OptimizationNode/OptimizationDetails.tsx
  src-frontend/src/OptimizationResults.tsx
  src-frontend/src/ReactFlow/OverlayButtons/NodeMenu/DetermineMassFlowRateButton.tsx
  src-frontend/src/ReactFlow/OverlayButtons/OptimizeButton.tsx
  src-frontend/src/ReactFlow/OverlayButtons/optimization-button.css
  src-frontend/src/models.ts
  src-frontend/src/utils/defaults.ts
Labels: enhancement, frontend

#85 Added example for group A4
  example/Grid-A4-v1.json
  example/Grid-A4.json
Labels: documentation, enhancement

#234 Added massenstrom property
  src/dto/OptimizedNodeResponse.kt
  src/dto/OptimizedPipeResponse.kt
  src/model/Node.kt
  src/model/Pipe.kt
  src/model/math/NodeMassenstromDelegate.kt
  src/model/math/NodeVolumeFlowDelegate.kt
  src/model/math/PipeMassenstromDelegate.kt
  src/model/math/PipeVolumeFlowDelegate.kt
  src/services/OptimizerService.kt
  src/util/MathUtil.kt
Labels: enhancement

#236 Seperated longest path from critical path
  src/model/Grid.kt
  src/model/Node.kt
  src/model/Optimizer.kt
  src/model/strategies/CrazyStrategy.kt
  src/model/strategies/CriticalPathAsOne.kt
  src/model/strategies/CriticalPathOneByOne.kt
  src/model/strategies/CriticalPathOneByOneReversed.kt
  src/model/strategies/LowerHeatLoss2.kt
  src/model/strategies/LowerPressureLoss10.kt
  src/model/strategies/LowerPressureLoss4.kt
  src/model/strategies/LowerPressureLoss6.kt
  src/services/OptimizerService.kt
  src/util/GridUtil.kt
  test/model/GridOptimizerTest.kt
Labels: enhancement

#237 Added basic excel support
  build.gradle.kts
  src/model/InvestmentParameter.kt
  src/util/DoubleUtil.kt
  src/util/ExcelUtil.kt
  src/util/FileUtil.kt
  test/model/GridOptimizerTest.kt
Labels: backend, enhancement
